//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.468
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceLinkedDataClient.ECommerceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MySoapFault", Namespace="http://schemas.datacontract.org/2004/07/ECommerceServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class MySoapFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoreDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoreDetails {
            get {
                return this.MoreDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.MoreDetailsField, value) != true)) {
                    this.MoreDetailsField = value;
                    this.RaisePropertyChanged("MoreDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationField, value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderMode", Namespace="http://schemas.datacontract.org/2004/07/ECommerceServiceLibrary")]
    public enum OrderMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductName = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SameCategory = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerTbl", Namespace="http://schemas.datacontract.org/2004/07/ECommerceServiceLibrary", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class CustomerTbl : ECommerceLinkedDataClient.ECommerceService.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ECommerceLinkedDataClient.ECommerceService.BestCustomersTbl[] BestCustomersTblsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CfamilyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastLoginDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastPurchaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LoggedInDurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumberOfLoginsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumberOfPurchasesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ECommerceLinkedDataClient.ECommerceService.PurchaseTbl[] PurchaseTblsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ECommerceLinkedDataClient.ECommerceService.BestCustomersTbl[] BestCustomersTbls {
            get {
                return this.BestCustomersTblsField;
            }
            set {
                if ((object.ReferenceEquals(this.BestCustomersTblsField, value) != true)) {
                    this.BestCustomersTblsField = value;
                    this.RaisePropertyChanged("BestCustomersTbls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cfamily {
            get {
                return this.CfamilyField;
            }
            set {
                if ((object.ReferenceEquals(this.CfamilyField, value) != true)) {
                    this.CfamilyField = value;
                    this.RaisePropertyChanged("Cfamily");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cid {
            get {
                return this.CidField;
            }
            set {
                if ((this.CidField.Equals(value) != true)) {
                    this.CidField = value;
                    this.RaisePropertyChanged("Cid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cname {
            get {
                return this.CnameField;
            }
            set {
                if ((object.ReferenceEquals(this.CnameField, value) != true)) {
                    this.CnameField = value;
                    this.RaisePropertyChanged("Cname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastLoginDate {
            get {
                return this.LastLoginDateField;
            }
            set {
                if ((this.LastLoginDateField.Equals(value) != true)) {
                    this.LastLoginDateField = value;
                    this.RaisePropertyChanged("LastLoginDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastPurchaseDate {
            get {
                return this.LastPurchaseDateField;
            }
            set {
                if ((this.LastPurchaseDateField.Equals(value) != true)) {
                    this.LastPurchaseDateField = value;
                    this.RaisePropertyChanged("LastPurchaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LoggedInDuration {
            get {
                return this.LoggedInDurationField;
            }
            set {
                if ((this.LoggedInDurationField.Equals(value) != true)) {
                    this.LoggedInDurationField = value;
                    this.RaisePropertyChanged("LoggedInDuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumberOfLogins {
            get {
                return this.NumberOfLoginsField;
            }
            set {
                if ((this.NumberOfLoginsField.Equals(value) != true)) {
                    this.NumberOfLoginsField = value;
                    this.RaisePropertyChanged("NumberOfLogins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumberOfPurchases {
            get {
                return this.NumberOfPurchasesField;
            }
            set {
                if ((this.NumberOfPurchasesField.Equals(value) != true)) {
                    this.NumberOfPurchasesField = value;
                    this.RaisePropertyChanged("NumberOfPurchases");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ECommerceLinkedDataClient.ECommerceService.PurchaseTbl[] PurchaseTbls {
            get {
                return this.PurchaseTblsField;
            }
            set {
                if ((object.ReferenceEquals(this.PurchaseTblsField, value) != true)) {
                    this.PurchaseTblsField = value;
                    this.RaisePropertyChanged("PurchaseTbls");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.BestCustomersTbl))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.PurchaseTbl))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.CustomerTbl))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.BestCustomersTbl))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.PurchaseTbl))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.CustomerTbl))]
    public partial class EntityObject : ECommerceLinkedDataClient.ECommerceService.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ECommerceLinkedDataClient.ECommerceService.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ECommerceLinkedDataClient.ECommerceService.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BestCustomersTbl", Namespace="http://schemas.datacontract.org/2004/07/ECommerceServiceLibrary", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class BestCustomersTbl : ECommerceLinkedDataClient.ECommerceService.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClusterIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ECommerceLinkedDataClient.ECommerceService.CustomerTbl CustomerTblField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ECommerceLinkedDataClient.ECommerceService.EntityReferenceOfCustomerTblqmSm1zCD CustomerTblReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cid {
            get {
                return this.CidField;
            }
            set {
                if ((this.CidField.Equals(value) != true)) {
                    this.CidField = value;
                    this.RaisePropertyChanged("Cid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClusterId {
            get {
                return this.ClusterIdField;
            }
            set {
                if ((this.ClusterIdField.Equals(value) != true)) {
                    this.ClusterIdField = value;
                    this.RaisePropertyChanged("ClusterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ECommerceLinkedDataClient.ECommerceService.CustomerTbl CustomerTbl {
            get {
                return this.CustomerTblField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTblField, value) != true)) {
                    this.CustomerTblField = value;
                    this.RaisePropertyChanged("CustomerTbl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ECommerceLinkedDataClient.ECommerceService.EntityReferenceOfCustomerTblqmSm1zCD CustomerTblReference {
            get {
                return this.CustomerTblReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTblReferenceField, value) != true)) {
                    this.CustomerTblReferenceField = value;
                    this.RaisePropertyChanged("CustomerTblReference");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseTbl", Namespace="http://schemas.datacontract.org/2004/07/ECommerceServiceLibrary", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class PurchaseTbl : ECommerceLinkedDataClient.ECommerceService.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ECommerceLinkedDataClient.ECommerceService.CustomerTbl CustomerTblField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ECommerceLinkedDataClient.ECommerceService.EntityReferenceOfCustomerTblqmSm1zCD CustomerTblReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PurchaseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> QuantityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cid {
            get {
                return this.CidField;
            }
            set {
                if ((this.CidField.Equals(value) != true)) {
                    this.CidField = value;
                    this.RaisePropertyChanged("Cid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ECommerceLinkedDataClient.ECommerceService.CustomerTbl CustomerTbl {
            get {
                return this.CustomerTblField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTblField, value) != true)) {
                    this.CustomerTblField = value;
                    this.RaisePropertyChanged("CustomerTbl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ECommerceLinkedDataClient.ECommerceService.EntityReferenceOfCustomerTblqmSm1zCD CustomerTblReference {
            get {
                return this.CustomerTblReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTblReferenceField, value) != true)) {
                    this.CustomerTblReferenceField = value;
                    this.RaisePropertyChanged("CustomerTblReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PurchaseId {
            get {
                return this.PurchaseIdField;
            }
            set {
                if ((this.PurchaseIdField.Equals(value) != true)) {
                    this.PurchaseIdField = value;
                    this.RaisePropertyChanged("PurchaseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ECommerceLinkedDataClient.ECommerceService.EntityKeyMember[] EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ECommerceLinkedDataClient.ECommerceService.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.OrderMode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.MySoapFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.CustomerTbl[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.CustomerTbl))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.BestCustomersTbl[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.BestCustomersTbl))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.PurchaseTbl[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.PurchaseTbl))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(int[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(int[][]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.EntityReferenceOfCustomerTblqmSm1zCD))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.EntityKeyMember[]))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfCustomerTblqmSm1zCD", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfCustomerTblqmSm1zCD : ECommerceLinkedDataClient.ECommerceService.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.EntityReferenceOfCustomerTblqmSm1zCD))]
    public partial class EntityReference : ECommerceLinkedDataClient.ECommerceService.RelatedEnd {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ECommerceLinkedDataClient.ECommerceService.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ECommerceLinkedDataClient.ECommerceService.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.EntityReferenceOfCustomerTblqmSm1zCD))]
    public partial class RelatedEnd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ECommerceService.IECommerceService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IECommerceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IECommerceService/Init", ReplyAction="http://tempuri.org/IECommerceService/InitResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.MySoapFault), Action="http://tempuri.org/IECommerceService/InitMySoapFaultFault", Name="MySoapFault", Namespace="http://schemas.datacontract.org/2004/07/ECommerceServiceLibrary")]
        void Init();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IECommerceService/FindRelatives", ReplyAction="http://tempuri.org/IECommerceService/FindRelativesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.MySoapFault), Action="http://tempuri.org/IECommerceService/FindRelativesMySoapFaultFault", Name="MySoapFault", Namespace="http://schemas.datacontract.org/2004/07/ECommerceServiceLibrary")]
        string[] FindRelatives(string productName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IECommerceService/FindAllRelatives", ReplyAction="http://tempuri.org/IECommerceService/FindAllRelativesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.MySoapFault), Action="http://tempuri.org/IECommerceService/FindAllRelativesMySoapFaultFault", Name="MySoapFault", Namespace="http://schemas.datacontract.org/2004/07/ECommerceServiceLibrary")]
        string[] FindAllRelatives(string[] productNames, ECommerceLinkedDataClient.ECommerceService.OrderMode mode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IECommerceService/FindCategoryName", ReplyAction="http://tempuri.org/IECommerceService/FindCategoryNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.MySoapFault), Action="http://tempuri.org/IECommerceService/FindCategoryNameMySoapFaultFault", Name="MySoapFault", Namespace="http://schemas.datacontract.org/2004/07/ECommerceServiceLibrary")]
        string FindCategoryName(string productName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IECommerceService/ListAds", ReplyAction="http://tempuri.org/IECommerceService/ListAdsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.MySoapFault), Action="http://tempuri.org/IECommerceService/ListAdsMySoapFaultFault", Name="MySoapFault", Namespace="http://schemas.datacontract.org/2004/07/ECommerceServiceLibrary")]
        string[] ListAds();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IECommerceService/GetPersonsDetail", ReplyAction="http://tempuri.org/IECommerceService/GetPersonsDetailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.MySoapFault), Action="http://tempuri.org/IECommerceService/GetPersonsDetailMySoapFaultFault", Name="MySoapFault", Namespace="http://schemas.datacontract.org/2004/07/ECommerceServiceLibrary")]
        ECommerceLinkedDataClient.ECommerceService.CustomerTbl[] GetPersonsDetail(int[] persons);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IECommerceService/SuggestProducts", ReplyAction="http://tempuri.org/IECommerceService/SuggestProductsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.MySoapFault), Action="http://tempuri.org/IECommerceService/SuggestProductsMySoapFaultFault", Name="MySoapFault", Namespace="http://schemas.datacontract.org/2004/07/ECommerceServiceLibrary")]
        string[] SuggestProducts(int personId, ECommerceLinkedDataClient.ECommerceService.OrderMode mode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IECommerceService/SuggestPersons", ReplyAction="http://tempuri.org/IECommerceService/SuggestPersonsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.MySoapFault), Action="http://tempuri.org/IECommerceService/SuggestPersonsMySoapFaultFault", Name="MySoapFault", Namespace="http://schemas.datacontract.org/2004/07/ECommerceServiceLibrary")]
        int[] SuggestPersons(string productName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IECommerceService/FindBestCustomers", ReplyAction="http://tempuri.org/IECommerceService/FindBestCustomersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.MySoapFault), Action="http://tempuri.org/IECommerceService/FindBestCustomersMySoapFaultFault", Name="MySoapFault", Namespace="http://schemas.datacontract.org/2004/07/ECommerceServiceLibrary")]
        int[][] FindBestCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IECommerceService/SuggestCustomersInTheirCluster", ReplyAction="http://tempuri.org/IECommerceService/SuggestCustomersInTheirClusterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ECommerceLinkedDataClient.ECommerceService.MySoapFault), Action="http://tempuri.org/IECommerceService/SuggestCustomersInTheirClusterMySoapFaultFau" +
            "lt", Name="MySoapFault", Namespace="http://schemas.datacontract.org/2004/07/ECommerceServiceLibrary")]
        int[][] SuggestCustomersInTheirCluster(string product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IECommerceService/AdvertiseNow", ReplyAction="http://tempuri.org/IECommerceService/AdvertiseNowResponse")]
        void AdvertiseNow();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IECommerceService/GiveMeCount", ReplyAction="http://tempuri.org/IECommerceService/GiveMeCountResponse")]
        int GiveMeCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IECommerceService/GetData", ReplyAction="http://tempuri.org/IECommerceService/GetDataResponse")]
        string GetData(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IECommerceServiceChannel : ECommerceLinkedDataClient.ECommerceService.IECommerceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ECommerceServiceClient : System.ServiceModel.ClientBase<ECommerceLinkedDataClient.ECommerceService.IECommerceService>, ECommerceLinkedDataClient.ECommerceService.IECommerceService {
        
        public ECommerceServiceClient() {
        }
        
        public ECommerceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ECommerceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ECommerceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ECommerceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Init() {
            base.Channel.Init();
        }
        
        public string[] FindRelatives(string productName) {
            return base.Channel.FindRelatives(productName);
        }
        
        public string[] FindAllRelatives(string[] productNames, ECommerceLinkedDataClient.ECommerceService.OrderMode mode) {
            return base.Channel.FindAllRelatives(productNames, mode);
        }
        
        public string FindCategoryName(string productName) {
            return base.Channel.FindCategoryName(productName);
        }
        
        public string[] ListAds() {
            return base.Channel.ListAds();
        }
        
        public ECommerceLinkedDataClient.ECommerceService.CustomerTbl[] GetPersonsDetail(int[] persons) {
            return base.Channel.GetPersonsDetail(persons);
        }
        
        public string[] SuggestProducts(int personId, ECommerceLinkedDataClient.ECommerceService.OrderMode mode) {
            return base.Channel.SuggestProducts(personId, mode);
        }
        
        public int[] SuggestPersons(string productName) {
            return base.Channel.SuggestPersons(productName);
        }
        
        public int[][] FindBestCustomers() {
            return base.Channel.FindBestCustomers();
        }
        
        public int[][] SuggestCustomersInTheirCluster(string product) {
            return base.Channel.SuggestCustomersInTheirCluster(product);
        }
        
        public void AdvertiseNow() {
            base.Channel.AdvertiseNow();
        }
        
        public int GiveMeCount() {
            return base.Channel.GiveMeCount();
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
    }
}
