//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.454
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceServiceLibrary.LinkedDataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatasourceFileType", Namespace="http://schemas.datacontract.org/2004/07/LinkedDataServiceLibrary")]
    public enum DatasourceFileType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rdfxml = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NTriples = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MySoapFault", Namespace="http://schemas.datacontract.org/2004/07/LinkedDataServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class MySoapFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoreDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoreDetails {
            get {
                return this.MoreDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.MoreDetailsField, value) != true)) {
                    this.MoreDetailsField = value;
                    this.RaisePropertyChanged("MoreDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationField, value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyResults", Namespace="http://schemas.datacontract.org/2004/07/LinkedDataServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class MyResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ECommerceServiceLibrary.LinkedDataService.QueryResult[] itemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string queryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ECommerceServiceLibrary.LinkedDataService.QueryResult[] items {
            get {
                return this.itemsField;
            }
            set {
                if ((object.ReferenceEquals(this.itemsField, value) != true)) {
                    this.itemsField = value;
                    this.RaisePropertyChanged("items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string query {
            get {
                return this.queryField;
            }
            set {
                if ((object.ReferenceEquals(this.queryField, value) != true)) {
                    this.queryField = value;
                    this.RaisePropertyChanged("query");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResult", Namespace="http://schemas.datacontract.org/2004/07/LinkedDataServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class QueryResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] variablesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] variables {
            get {
                return this.variablesField;
            }
            set {
                if ((object.ReferenceEquals(this.variablesField, value) != true)) {
                    this.variablesField = value;
                    this.RaisePropertyChanged("variables");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://MyLinkedDataCodes.com/wcf", ConfigurationName="LinkedDataService.LinkedDataWcfService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface LinkedDataWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MyLinkedDataCodes.com/wcf/LinkedDataWcfService/Init", ReplyAction="http://MyLinkedDataCodes.com/wcf/LinkedDataWcfService/InitResponse")]
        void Init();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MyLinkedDataCodes.com/wcf/LinkedDataWcfService/AddTripleWithUriSubject", ReplyAction="http://MyLinkedDataCodes.com/wcf/LinkedDataWcfService/AddTripleWithUriSubjectResp" +
            "onse")]
        void AddTripleWithUriSubject(string subject, string predicate, string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MyLinkedDataCodes.com/wcf/LinkedDataWcfService/AddTripleWithLiteralSubject" +
            "", ReplyAction="http://MyLinkedDataCodes.com/wcf/LinkedDataWcfService/AddTripleWithLiteralSubject" +
            "Response")]
        void AddTripleWithLiteralSubject(string subject, string predicate, string obj, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MyLinkedDataCodes.com/wcf/LinkedDataWcfService/LoadFromFile", ReplyAction="http://MyLinkedDataCodes.com/wcf/LinkedDataWcfService/LoadFromFileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ECommerceServiceLibrary.LinkedDataService.MySoapFault), Action="http://MyLinkedDataCodes.com/wcf/LinkedDataWcfService/LoadFromFileMySoapFaultFaul" +
            "t", Name="MySoapFault", Namespace="http://schemas.datacontract.org/2004/07/LinkedDataServiceLibrary")]
        void LoadFromFile(string filePath, ECommerceServiceLibrary.LinkedDataService.DatasourceFileType fileType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MyLinkedDataCodes.com/wcf/LinkedDataWcfService/SaveToFile", ReplyAction="http://MyLinkedDataCodes.com/wcf/LinkedDataWcfService/SaveToFileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ECommerceServiceLibrary.LinkedDataService.MySoapFault), Action="http://MyLinkedDataCodes.com/wcf/LinkedDataWcfService/SaveToFileMySoapFaultFault", Name="MySoapFault", Namespace="http://schemas.datacontract.org/2004/07/LinkedDataServiceLibrary")]
        void SaveToFile(string filePath, ECommerceServiceLibrary.LinkedDataService.DatasourceFileType fileType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MyLinkedDataCodes.com/wcf/LinkedDataWcfService/ExceuteQuery", ReplyAction="http://MyLinkedDataCodes.com/wcf/LinkedDataWcfService/ExceuteQueryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ECommerceServiceLibrary.LinkedDataService.MySoapFault), Action="http://MyLinkedDataCodes.com/wcf/LinkedDataWcfService/ExceuteQueryMySoapFaultFaul" +
            "t", Name="MySoapFault", Namespace="http://schemas.datacontract.org/2004/07/LinkedDataServiceLibrary")]
        ECommerceServiceLibrary.LinkedDataService.MyResults ExceuteQuery(string query);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://MyLinkedDataCodes.com/wcf/LinkedDataWcfService/LoadDefaultDatasourceFile")]
        void LoadDefaultDatasourceFile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MyLinkedDataCodes.com/wcf/LinkedDataWcfService/SetMyName", ReplyAction="http://MyLinkedDataCodes.com/wcf/LinkedDataWcfService/SetMyNameResponse")]
        void SetMyName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MyLinkedDataCodes.com/wcf/LinkedDataWcfService/SayHello", ReplyAction="http://MyLinkedDataCodes.com/wcf/LinkedDataWcfService/SayHelloResponse")]
        string SayHello();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LinkedDataWcfServiceChannel : ECommerceServiceLibrary.LinkedDataService.LinkedDataWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LinkedDataWcfServiceClient : System.ServiceModel.ClientBase<ECommerceServiceLibrary.LinkedDataService.LinkedDataWcfService>, ECommerceServiceLibrary.LinkedDataService.LinkedDataWcfService {
        
        public LinkedDataWcfServiceClient() {
        }
        
        public LinkedDataWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LinkedDataWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LinkedDataWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LinkedDataWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Init() {
            base.Channel.Init();
        }
        
        public void AddTripleWithUriSubject(string subject, string predicate, string obj) {
            base.Channel.AddTripleWithUriSubject(subject, predicate, obj);
        }
        
        public void AddTripleWithLiteralSubject(string subject, string predicate, string obj, string language) {
            base.Channel.AddTripleWithLiteralSubject(subject, predicate, obj, language);
        }
        
        public void LoadFromFile(string filePath, ECommerceServiceLibrary.LinkedDataService.DatasourceFileType fileType) {
            base.Channel.LoadFromFile(filePath, fileType);
        }
        
        public void SaveToFile(string filePath, ECommerceServiceLibrary.LinkedDataService.DatasourceFileType fileType) {
            base.Channel.SaveToFile(filePath, fileType);
        }
        
        public ECommerceServiceLibrary.LinkedDataService.MyResults ExceuteQuery(string query) {
            return base.Channel.ExceuteQuery(query);
        }
        
        public void LoadDefaultDatasourceFile() {
            base.Channel.LoadDefaultDatasourceFile();
        }
        
        public void SetMyName(string name) {
            base.Channel.SetMyName(name);
        }
        
        public string SayHello() {
            return base.Channel.SayHello();
        }
    }
}
